data InactiveEmployees;
	DROP DateofBirth3 Dateofresignation3 DateofJoin3	DateOfRelieving3	ShiftEffectiveFrom3	FacilityEffectiveFrom3	RptEffectiveFrom3	LastReviewDate3	LastButOneReviewDate3	ProjectEffectiveFrom3;
	set SASEDWFW.AttAnalysis_tblInActiveEmployees (RENAME=(Dateofresignation = Dateofresignation3 DateofJoin = DateofJoin3 DateofBirth=DateofBirth3 DateOfRelieving = DateOfRelieving3 ShiftEffectiveFrom=ShiftEffectiveFrom3 FacilityEffectiveFrom=FacilityEffectiveFrom3 RptEffectiveFrom=RptEffectiveFrom3 LastReviewDate=LastReviewDate3 LastButOneReviewDate=LastButOneReviewDate3 ProjectEffectiveFrom=ProjectEffectiveFrom3));
		if DateofJoin3 ne '' then DateofJoin = input(DateofJoin3, yymmdd10.);
		if DateofBirth3 ne '' then DateofBirth = input(DateofBirth3, yymmdd10.);
		if DateOfRelieving3 ne '' then DateOfRelieving = input(DateOfRelieving3, yymmdd10.);
		if ShiftEffectiveFrom3 ne '' then ShiftEffectiveFrom=input(ShiftEffectiveFrom3, mmddyy10.);
		if FacilityEffectiveFrom3 ne '' then FacilityEffectiveFrom = input(FacilityEffectiveFrom3, yymmdd10.);
		if RptEffectiveFrom3 ne '' then RptEffectiveFrom = input(RptEffectiveFrom3,  yymmdd10.);
		if LastReviewDate3 ne '' then LastReviewDate = input(LastReviewDate3,yymmdd10.);
		if LastButOneReviewDate3 ne '' then LastButOneReviewDate=input(LastButOneReviewDate3,yymmdd10.);
		if ProjectEffectiveFrom3 ne '' then ProjectEffectiveFrom = input(ProjectEffectiveFrom3,mmddyy10.);
		if Dateofresignation3 ne '' then Dateofresignation = input(Dateofresignation3,yymmdd10.);
	format DateofJoin Dateofresignation DateofBirth DateOfRelieving ShiftEffectiveFrom FacilityEffectiveFrom RptEffectiveFrom LastReviewDate LastButOneReviewDate ProjectEffectiveFrom mmddyy10.;
run;
data activeEmployees;
DROP DateofBirth3 Dateofresignation3	DateofJoin3	DateOfRelieving3	ShiftEffectiveFrom3	FacilityEffectiveFrom3	RptEffectiveFrom3	LastReviewDate3	LastButOneReviewDate3	ProjectEffectiveFrom3;
	set SASEDWFW.AttAnalysis_tblActiveEmployees (RENAME=(Dateofresignation=Dateofresignation3 DateofJoin = DateofJoin3 DateofBirth=DateofBirth3 DateOfRelieving = DateOfRelieving3 ShiftEffectiveFrom=ShiftEffectiveFrom3 FacilityEffectiveFrom=FacilityEffectiveFrom3 RptEffectiveFrom=RptEffectiveFrom3 LastReviewDate=LastReviewDate3 LastButOneReviewDate=LastButOneReviewDate3 ProjectEffectiveFrom=ProjectEffectiveFrom3));
		if DateofJoin3 ne '' then DateofJoin = input(DateofJoin3, yymmdd10.);
		if DateofBirth3 ne '' then DateofBirth = input(DateofBirth3, yymmdd10.);
		if DateOfRelieving3 ne '' then DateOfRelieving = input(DateOfRelieving3, yymmdd10.);
		if ShiftEffectiveFrom3 ne '' then ShiftEffectiveFrom=input(ShiftEffectiveFrom3, mmddyy10.);
		if FacilityEffectiveFrom3 ne '' then FacilityEffectiveFrom = input(FacilityEffectiveFrom3, yymmdd10.);
		if RptEffectiveFrom3 ne '' then RptEffectiveFrom = input(RptEffectiveFrom3,  yymmdd10.);
		if LastReviewDate3 ne '' then LastReviewDate = input(LastReviewDate3,yymmdd10.);
		if LastButOneReviewDate3 ne '' then LastButOneReviewDate=input(LastButOneReviewDate3,yymmdd10.);
		if ProjectEffectiveFrom3 ne '' then ProjectEffectiveFrom = input(ProjectEffectiveFrom3,mmddyy10.);
		if Dateofresignation3 ne '' then Dateofresignation = input(Dateofresignation3,yymmdd10.);
format DateofJoin Dateofresignation DateofBirth DateOfRelieving ShiftEffectiveFrom FacilityEffectiveFrom RptEffectiveFrom LastReviewDate LastButOneReviewDate ProjectEffectiveFrom mmddyy10.;
run;

data all;
set activeEmployees
InactiveEmployees;
run;